
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mufidatun
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Identitas = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        SA = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        ST = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        JK = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        Waktu = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        Harga = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        TD = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        T = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Cari = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        jLabel11.setFont(new java.awt.Font("Script MT Bold", 1, 24)); // NOI18N
        jLabel11.setText("Data Pemesanan Tiket");

        jButton7.setText("Pesan");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Clear");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel12.setText("Nama");

        Nama.setEnabled(false);
        Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaActionPerformed(evt);
            }
        });

        jLabel13.setText("Identitas");

        jLabel14.setText("Stasiun Awal");

        SA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Gambir", "Juanda", "Kemayoran", "Pasar Senen", "Banyuwangi Baru", "Jatiroto", "Jember", "Karangasem", "Kalisat", "Kalibaru", "Kalisetail", "Klakah", "Pasuruan", "Probolinggo", "Rambipuji", "Rogojampi", "Tanggul", "Temuguruh", "Blimbing", "Kepanjen", "Lawang", "Malang Kota Baru", "Malang Kota Lama", "Ngebruk", "Pakisaji", "Singosari", "Sumberpucung", "Gubeng", "Pasar Turi", "Surabaya Kota", "Wonokromo", "Tandes", "Kandangan", "Benowo" }));

        jLabel15.setText("Stasiun Tujuan");

        ST.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Gambir", "Juanda", "Kemayoran", "Pasar Senen", "Banyuwangi Baru", "Jatiroto", "Jember", "Karangasem", "Kalisat", "Kalibaru", "Kalisetail", "Klakah", "Pasuruan", "Probolinggo", "Rambipuji", "Rogojampi", "Tanggul", "Temuguruh", "Blimbing", "Kepanjen", "Lawang", "Malang Kota Baru", "Malang Kota Lama", "Ngebruk", "Pakisaji", "Singosari", "Sumberpucung", "Gubeng", "Pasar Turi", "Surabaya Kota", "Wonokromo", "Tandes", "Kandangan", "Benowo" }));

        jLabel16.setText("Jenis Kereta");

        JK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Ekonomi", "Bisnis", "Eksekutif" }));

        jLabel18.setText("Tanggal");

        jLabel7.setText("Waktu");

        jLabel19.setText("Harga");

        TD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "A1", "A2", "A3", "B1", "B2", "B3", "C1", "C2", "C3" }));
        TD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TDActionPerformed(evt);
            }
        });

        jLabel17.setText("Tempat Duduk");

        T.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "09.00", "12.00", "14.00", "16.00" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(Nama, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(Identitas, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(SA, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(90, 90, 90)
                            .addComponent(ST, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(JK, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(Waktu, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(T, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(49, 49, 49)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Harga, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TD, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel12))
                    .addComponent(Nama, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel13))
                    .addComponent(Identitas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel14))
                    .addComponent(SA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ST, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel16))
                    .addComponent(JK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel18))
                    .addComponent(Waktu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(T, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Harga, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addGap(29, 29, 29))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 400, 500);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Script MT Bold", 0, 36)); // NOI18N
        jLabel3.setText("Kenyamanan Anda");

        jLabel4.setFont(new java.awt.Font("Script MT Bold", 0, 36)); // NOI18N
        jLabel4.setText("Prioritas Bagi Kami");

        jPanel7.setBackground(new java.awt.Color(255, 0, 51));

        jLabel5.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Terimakasih Telah Mempercayakan");

        jLabel6.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Perjalanan Anda pada Kami");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel5))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel6)))
                .addContainerGap(355, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel3))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(96, 96, 96)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(370, 0, 530, 500);

        jTabbedPane1.addTab("Pemesanan", jPanel1);

        jPanel2.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama", "No.identitas", "Stasiun_awal", "Tujuan", "Jenis_Kereta", "Tanggal_berangkat", "Waktu_berangkat", "Tempat_duduk", "Harga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 250, 866, 200);

        jPanel5.setBackground(new java.awt.Color(255, 0, 51));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PT. Kereta Api Indonesia");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Kenyamanan Anda Adalah Prioritas Bagi Kami");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(323, 323, 323)
                .addComponent(jLabel1)
                .addContainerGap(342, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel5);
        jPanel5.setBounds(0, 0, 881, 120);

        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(0, 0, 51, 23);

        jPanel6.setBackground(new java.awt.Color(255, 255, 204));

        jButton3.setText("Refresh");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Print");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Close");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cari, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addGap(38, 38, 38)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(Cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(238, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel6);
        jPanel6.setBounds(0, 120, 880, 350);

        jTabbedPane1.addTab("Tiket", jPanel2);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 886, 510);

        setSize(new java.awt.Dimension(899, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TDActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat date = new SimpleDateFormat("dd-MM-yyyy");
            String waktu = date.format(Waktu.getDate());

        
        if ("".equals(Nama.getText()) ||"".equals(Identitas.getText()) ||"".equals(SA.getSelectedItem()) ||"".equals(ST.getSelectedItem()) ||"".equals(JK.getSelectedItem()) ||"".equals(Waktu.getDate()) || "".equals(T.getSelectedItem())||"".equals(TD.getSelectedItem())||"".equals(Harga.getText())) {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
            
            String SQL = "INSERT INTO `tb_tiket`(`Nama`, `No.identitas`, `Stasiun_awal`, `Tujuan`, `Jenis_kereta`, `Tanggal_berangkat`, `Waktu_berangkat`, `Tempat_duduk`, `Harga`)"
                    +"VALUES('" + Nama.getText() + "', '" + Identitas.getText() + "','"  + SA.getSelectedItem() + "','"+ST.getSelectedItem()+"','"+JK.getSelectedItem()+"','" + waktu + "','" + T.getSelectedItem() + "','"+TD.getSelectedItem() + "','" + Harga.getText() + "')";
            int status = KoneksiDB.execute(SQL);
            if (status == 1){
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Gagal", JOptionPane.WARNING_MESSAGE);
            }

        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          if ("".equals(Nama.getText()) ||"".equals(Identitas.getText()) ||"".equals(SA.getSelectedItem()) ||"".equals(ST.getSelectedItem()) ||"".equals(JK.getSelectedItem()) ||"".equals(Waktu.getDate()) || "".equals(TD.getSelectedItem())||"".equals(Harga.getText())) {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
             SimpleDateFormat date = new SimpleDateFormat("dd-MM-yyyy");
            String waktu = date.format(Waktu.getDate());
           
            String SQL = "UPDATE tb_tiket SET "
            + "Nama='"+Nama.getText()+"', "
            + "No_identitas='"+Identitas.getText()+"', "
            + "Stasiun_awal='"+SA.getSelectedItem()+"', "
            + "Tujuan='"+ST.getSelectedItem()+"', "
            + "Jenis_kereta='"+JK.getSelectedItem()+"', "
            + "Tanggal_Berangkat='"+waktu+"', "
            + "Tempat_duduk='"+TD.getSelectedItem()+"', "
            + "Harga='"+Harga.getText()+"' WHERE Nama='"+Nama.getText()+"'";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil diupdate", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal diupdate", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        selectData();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int baris = jTable1.getSelectedRow();
        if(baris != -1) {
            String Nama = jTable1.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM tb_tiket WHERE Nama ='"+Nama+"'";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih Dahulu", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Form Pembelian Tiket Kereta");
        MessageFormat footer = new MessageFormat("Page (0,number,integer)       ");
        try {
            jTable1.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Cannot print %s%n", e.getMessage());
        } 
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        Nama.setText("");
        Identitas.setText("");
        JK.setSelectedItem(" ");
        SA.setSelectedItem(" ");
        ST.setSelectedItem(" ");
        T.setSelectedItem(" ");
        TD.setSelectedItem(" ");
        Harga.setText("");
        Waktu.setDate(null);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        String halouser = Login.useraktif;
        Nama.setText(halouser);
        selectData();
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       public void Cari(){
        String kolom[] = {"Nama","No_identitas","Stasiun_awal","Tujuan","Jenis_Kereta","Tanggal_berangkat","Waktu_berangkat","Tempat_duduk", "Harga"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        
        SimpleDateFormat date2 = new SimpleDateFormat("dd-MM-yyyy");
        String CariTgl = date2.format(Cari.getDate());
        String SQL = "SELECT FROM tb_tiket WHERE Tanggal_berangkat = "+CariTgl+"";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        
        try {
            while(rs.next()){
                String Nama = rs.getString(1);
                String No_identitas = rs.getString(2);
                String Stasiun_awal = "";
                if ("Gambir".equals(rs.getString(3))) {
                    Stasiun_awal= "Gambir";
                } else if ("Juanda".equals(rs.getString(3))){
                    Stasiun_awal = "Juanda";
                } else if ("Kemayoran".equals(rs.getString(3))){
                    Stasiun_awal = "Kemayoran";
                } else if ("Pasar Senen".equals(rs.getString(3))){
                    Stasiun_awal = "Pasar Senen";
                } else if ("Banyuwangi Baru".equals(rs.getString(3))){
                    Stasiun_awal = "Banyuwangi Baru";
                } else if ("Jatiroto".equals(rs.getString(3))){
                    Stasiun_awal = "Jatiroto";
                } else if ("Jember".equals(rs.getString(3))){
                    Stasiun_awal = "Jember";
                } else if ("Karangasem".equals(rs.getString(3))){
                    Stasiun_awal = "Karangasem";
                } else if ("Kalisat".equals(rs.getString(3))){
                    Stasiun_awal = "Kalisat";
                } else if ("Kalibaru".equals(rs.getString(3))){
                    Stasiun_awal = "Kalibaru";
                } else if ("Kalisetail".equals(rs.getString(3))){
                    Stasiun_awal = "Kalisetail";
                } else if ("Klakah".equals(rs.getString(3))){
                    Stasiun_awal = "Klakah";
                } else if ("Pasuruan".equals(rs.getString(3))){
                    Stasiun_awal = "Pasuruan";
                } else if ("Probolinggo".equals(rs.getString(3))){
                    Stasiun_awal = "Probolinggo";
                } else if ("Rambipuji".equals(rs.getString(3))){
                    Stasiun_awal = "Rambipuji";
                } else if ("Rogojampi".equals(rs.getString(3))){
                    Stasiun_awal = "Rogojampi";
                } else if ("Tanggul".equals(rs.getString(3))){
                    Stasiun_awal = "Tanggul";
                } else if ("Temuguruh".equals(rs.getString(3))){
                    Stasiun_awal = "Temuguruh";
                } else if ("Blimbing".equals(rs.getString(3))){
                    Stasiun_awal = "Blimbing";
                } else if ("Kepanjen".equals(rs.getString(3))){
                    Stasiun_awal = "Kepanjen";
                } else if ("Lawang".equals(rs.getString(3))){
                    Stasiun_awal = "Lawang";
                } else if ("Malang Kota Baru".equals(rs.getString(3))){
                    Stasiun_awal = "Malang Kota Baru";
                } else if ("Malang Kota Lama".equals(rs.getString(3))){
                    Stasiun_awal = "Malang Kota Lama";
                } else if ("Ngebruk".equals(rs.getString(3))){
                    Stasiun_awal = "Ngebruk";
                } else if ("Pakisaji".equals(rs.getString(3))){
                    Stasiun_awal = "Pakisaji";
                } else if ("Singosari".equals(rs.getString(3))){
                    Stasiun_awal = "Singosari";
                } else if ("Sumberpucung".equals(rs.getString(3))){
                    Stasiun_awal = "Sumberpucung";
                } else if ("Gubeng".equals(rs.getString(3))){
                    Stasiun_awal = "Gubeng";
                } else if ("Pasar Turi".equals(rs.getString(3))){
                    Stasiun_awal = "Pasar Turi";
                } else if ("Surabaya Kota".equals(rs.getString(3))){
                    Stasiun_awal = "Surabaya Kota";
                } else if ("Wonokromo".equals(rs.getString(3))){
                    Stasiun_awal = "Wonokromo";
                } else if ("Tandes".equals(rs.getString(3))){
                    Stasiun_awal = "Tandes";
                } else if ("Kandangan".equals(rs.getString(3))){
                    Stasiun_awal = "Kandangan";                    
                } else {
                    Stasiun_awal = "Benowo";
                }
                String Tujuan = "";
                if ("Gambir".equals(rs.getString(4))) {
                    Tujuan = "Gambir";
                } else if ("Juanda".equals(rs.getString(4))){
                    Tujuan = "Juanda";
                } else if ("Kemayoran".equals(rs.getString(4))){
                    Tujuan = "Kemayoran";
                } else if ("Pasar Senen".equals(rs.getString(4))){
                    Tujuan = "Pasar Senen";
                } else if ("Banyuwangi Baru".equals(rs.getString(4))){
                    Tujuan = "Banyuwangi Baru";
                } else if ("Jatiroto".equals(rs.getString(4))){
                    Tujuan = "Jatiroto";
                } else if ("Jember".equals(rs.getString(4))){
                    Tujuan = "Jember";
                } else if ("Karangasem".equals(rs.getString(4))){
                    Tujuan = "Karangasem";
                } else if ("Kalisat".equals(rs.getString(4))){
                    Tujuan = "Kalisat";
                } else if ("Kalibaru".equals(rs.getString(4))){
                    Tujuan = "Kalibaru";
                } else if ("Kalisetail".equals(rs.getString(4))){
                    Tujuan = "Kalisetail";
                } else if ("Klakah".equals(rs.getString(4))){
                    Tujuan = "Klakah";
                } else if ("Pasuruan".equals(rs.getString(4))){
                    Tujuan = "Pasuruan";
                } else if ("Probolinggo".equals(rs.getString(4))){
                    Tujuan = "Probolinggo";
                } else if ("Rambipuji".equals(rs.getString(4))){
                    Tujuan = "Rambipuji";
                } else if ("Rogojampi".equals(rs.getString(4))){
                    Tujuan = "Rogojampi";
                } else if ("Tanggul".equals(rs.getString(4))){
                    Tujuan = "Tanggul";
                } else if ("Temuguruh".equals(rs.getString(4))){
                    Tujuan = "Temuguruh";
                } else if ("Blimbing".equals(rs.getString(4))){
                    Tujuan = "Blimbing";
                } else if ("Kepanjen".equals(rs.getString(4))){
                    Tujuan = "Kepanjen";
                } else if ("Lawang".equals(rs.getString(4))){
                    Tujuan = "Lawang";
                } else if ("Malang Kota Baru".equals(rs.getString(4))){
                    Tujuan = "Malang Kota Baru";
                } else if ("Malang Kota Lama".equals(rs.getString(4))){
                    Tujuan = "Malang Kota Lama";
                } else if ("Ngebruk".equals(rs.getString(4))){
                    Tujuan = "Ngebruk";
                } else if ("Pakisaji".equals(rs.getString(4))){
                    Tujuan = "Pakisaji";
                } else if ("Singosari".equals(rs.getString(4))){
                    Tujuan = "Singosari";
                } else if ("Sumberpucung".equals(rs.getString(4))){
                    Tujuan = "Sumberpucung";
                } else if ("Gubeng".equals(rs.getString(4))){
                    Tujuan = "Gubeng";
                } else if ("Pasar Turi".equals(rs.getString(4))){
                    Tujuan = "Pasar Turi";
                } else if ("Surabaya Kota".equals(rs.getString(4))){
                    Tujuan = "Surabaya Kota";
                } else if ("Wonokromo".equals(rs.getString(4))){
                    Tujuan = "Wonokromo";
                } else if ("Tandes".equals(rs.getString(4))){
                    Tujuan = "Tandes";
                } else if ("Kandangan".equals(rs.getString(4))){
                    Tujuan = "Kandangan";                    
                } else {
                    Tujuan = "Benowo";
                }
                String Jenis_Kereta = "";
                if ("Ekonomi".equals(rs.getString(5))) {
                    Jenis_Kereta = "Ekonomi";
                } else if ("Bisnis".equals(rs.getString(5))){
                    Jenis_Kereta = "Bisnis";
                } else {
                    Jenis_Kereta = "Eksekutif";
                }
                String Tanggal_berangkat = rs.getString(6);
                String Waktu_berangkat = "";
                if ("09.00".equals(rs.getString(7))) {
                    Waktu_berangkat = "09.00";
                } else if ("12.00".equals(rs.getString(7))) {
                    Waktu_berangkat = "12.00";
                } else if ("14.00".equals(rs.getString(7))) {
                    Waktu_berangkat = "14.00";
                } else {
                    Waktu_berangkat = "16.00";
                }
                
                String Tempat_duduk = "";
                if ("A1".equals(rs.getString(8))) {
                    Tempat_duduk = "A1";
                } else if ("A2".equals(rs.getString(8))) {
                    Tempat_duduk = "A2";
                } else if ("A3".equals(rs.getString(8))) {
                    Tempat_duduk = "A3";
                } else if ("B1".equals(rs.getString(8))) {
                    Tempat_duduk = "B1";
                } else if ("B2".equals(rs.getString(8))) {
                    Tempat_duduk = "B2";
                } else if ("B3".equals(rs.getString(8))) {
                    Tempat_duduk = "B3";
                } else if ("C1".equals(rs.getString(8))) {
                    Tempat_duduk = "C1";
                } else if ("C2".equals(rs.getString(8))) {
                    Tempat_duduk = "C2";
                }else  {
                    Tempat_duduk = "C3";
                }
                String Harga = rs.getString(9);
    
                String data[] = {Nama,No_identitas,Stasiun_awal,Tujuan,Jenis_Kereta,Tanggal_berangkat,Waktu_berangkat,Tempat_duduk, Harga};
                dtm.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTable1.setModel(dtm);
    }
                    
    }//GEN-LAST:event_jButton1ActionPerformed

    public void selectData(){
        String kolom[] = {"Nama","No_identitas","Stasiun_awal","Tujuan","Jenis_Kereta","Tanggal_berangkat","Waktu_berangkat","Tempat_duduk", "Harga"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM tb_tiket";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        
        try {
            while(rs.next()){
                String Nama = rs.getString(1);
                String No_identitas = rs.getString(2);
                String Stasiun_awal = "";
                if ("Gambir".equals(rs.getString(3))) {
                    Stasiun_awal= "Gambir";
                } else if ("Juanda".equals(rs.getString(3))){
                    Stasiun_awal = "Juanda";
                } else if ("Kemayoran".equals(rs.getString(3))){
                    Stasiun_awal = "Kemayoran";
                } else if ("Pasar Senen".equals(rs.getString(3))){
                    Stasiun_awal = "Pasar Senen";
                } else if ("Banyuwangi Baru".equals(rs.getString(3))){
                    Stasiun_awal = "Banyuwangi Baru";
                } else if ("Jatiroto".equals(rs.getString(3))){
                    Stasiun_awal = "Jatiroto";
                } else if ("Jember".equals(rs.getString(3))){
                    Stasiun_awal = "Jember";
                } else if ("Karangasem".equals(rs.getString(3))){
                    Stasiun_awal = "Karangasem";
                } else if ("Kalisat".equals(rs.getString(3))){
                    Stasiun_awal = "Kalisat";
                } else if ("Kalibaru".equals(rs.getString(3))){
                    Stasiun_awal = "Kalibaru";
                } else if ("Kalisetail".equals(rs.getString(3))){
                    Stasiun_awal = "Kalisetail";
                } else if ("Klakah".equals(rs.getString(3))){
                    Stasiun_awal = "Klakah";
                } else if ("Pasuruan".equals(rs.getString(3))){
                    Stasiun_awal = "Pasuruan";
                } else if ("Probolinggo".equals(rs.getString(3))){
                    Stasiun_awal = "Probolinggo";
                } else if ("Rambipuji".equals(rs.getString(3))){
                    Stasiun_awal = "Rambipuji";
                } else if ("Rogojampi".equals(rs.getString(3))){
                    Stasiun_awal = "Rogojampi";
                } else if ("Tanggul".equals(rs.getString(3))){
                    Stasiun_awal = "Tanggul";
                } else if ("Temuguruh".equals(rs.getString(3))){
                    Stasiun_awal = "Temuguruh";
                } else if ("Blimbing".equals(rs.getString(3))){
                    Stasiun_awal = "Blimbing";
                } else if ("Kepanjen".equals(rs.getString(3))){
                    Stasiun_awal = "Kepanjen";
                } else if ("Lawang".equals(rs.getString(3))){
                    Stasiun_awal = "Lawang";
                } else if ("Malang Kota Baru".equals(rs.getString(3))){
                    Stasiun_awal = "Malang Kota Baru";
                } else if ("Malang Kota Lama".equals(rs.getString(3))){
                    Stasiun_awal = "Malang Kota Lama";
                } else if ("Ngebruk".equals(rs.getString(3))){
                    Stasiun_awal = "Ngebruk";
                } else if ("Pakisaji".equals(rs.getString(3))){
                    Stasiun_awal = "Pakisaji";
                } else if ("Singosari".equals(rs.getString(3))){
                    Stasiun_awal = "Singosari";
                } else if ("Sumberpucung".equals(rs.getString(3))){
                    Stasiun_awal = "Sumberpucung";
                } else if ("Gubeng".equals(rs.getString(3))){
                    Stasiun_awal = "Gubeng";
                } else if ("Pasar Turi".equals(rs.getString(3))){
                    Stasiun_awal = "Pasar Turi";
                } else if ("Surabaya Kota".equals(rs.getString(3))){
                    Stasiun_awal = "Surabaya Kota";
                } else if ("Wonokromo".equals(rs.getString(3))){
                    Stasiun_awal = "Wonokromo";
                } else if ("Tandes".equals(rs.getString(3))){
                    Stasiun_awal = "Tandes";
                } else if ("Kandangan".equals(rs.getString(3))){
                    Stasiun_awal = "Kandangan";                    
                } else {
                    Stasiun_awal = "Benowo";
                }
                String Tujuan = "";
                if ("Gambir".equals(rs.getString(4))) {
                    Tujuan = "Gambir";
                } else if ("Juanda".equals(rs.getString(4))){
                    Tujuan = "Juanda";
                } else if ("Kemayoran".equals(rs.getString(4))){
                    Tujuan = "Kemayoran";
                } else if ("Pasar Senen".equals(rs.getString(4))){
                    Tujuan = "Pasar Senen";
                } else if ("Banyuwangi Baru".equals(rs.getString(4))){
                    Tujuan = "Banyuwangi Baru";
                } else if ("Jatiroto".equals(rs.getString(4))){
                    Tujuan = "Jatiroto";
                } else if ("Jember".equals(rs.getString(4))){
                    Tujuan = "Jember";
                } else if ("Karangasem".equals(rs.getString(4))){
                    Tujuan = "Karangasem";
                } else if ("Kalisat".equals(rs.getString(4))){
                    Tujuan = "Kalisat";
                } else if ("Kalibaru".equals(rs.getString(4))){
                    Tujuan = "Kalibaru";
                } else if ("Kalisetail".equals(rs.getString(4))){
                    Tujuan = "Kalisetail";
                } else if ("Klakah".equals(rs.getString(4))){
                    Tujuan = "Klakah";
                } else if ("Pasuruan".equals(rs.getString(4))){
                    Tujuan = "Pasuruan";
                } else if ("Probolinggo".equals(rs.getString(4))){
                    Tujuan = "Probolinggo";
                } else if ("Rambipuji".equals(rs.getString(4))){
                    Tujuan = "Rambipuji";
                } else if ("Rogojampi".equals(rs.getString(4))){
                    Tujuan = "Rogojampi";
                } else if ("Tanggul".equals(rs.getString(4))){
                    Tujuan = "Tanggul";
                } else if ("Temuguruh".equals(rs.getString(4))){
                    Tujuan = "Temuguruh";
                } else if ("Blimbing".equals(rs.getString(4))){
                    Tujuan = "Blimbing";
                } else if ("Kepanjen".equals(rs.getString(4))){
                    Tujuan = "Kepanjen";
                } else if ("Lawang".equals(rs.getString(4))){
                    Tujuan = "Lawang";
                } else if ("Malang Kota Baru".equals(rs.getString(4))){
                    Tujuan = "Malang Kota Baru";
                } else if ("Malang Kota Lama".equals(rs.getString(4))){
                    Tujuan = "Malang Kota Lama";
                } else if ("Ngebruk".equals(rs.getString(4))){
                    Tujuan = "Ngebruk";
                } else if ("Pakisaji".equals(rs.getString(4))){
                    Tujuan = "Pakisaji";
                } else if ("Singosari".equals(rs.getString(4))){
                    Tujuan = "Singosari";
                } else if ("Sumberpucung".equals(rs.getString(4))){
                    Tujuan = "Sumberpucung";
                } else if ("Gubeng".equals(rs.getString(4))){
                    Tujuan = "Gubeng";
                } else if ("Pasar Turi".equals(rs.getString(4))){
                    Tujuan = "Pasar Turi";
                } else if ("Surabaya Kota".equals(rs.getString(4))){
                    Tujuan = "Surabaya Kota";
                } else if ("Wonokromo".equals(rs.getString(4))){
                    Tujuan = "Wonokromo";
                } else if ("Tandes".equals(rs.getString(4))){
                    Tujuan = "Tandes";
                } else if ("Kandangan".equals(rs.getString(4))){
                    Tujuan = "Kandangan";                    
                } else {
                    Tujuan = "Benowo";
                }
                String Jenis_Kereta = "";
                if ("Ekonomi".equals(rs.getString(5))) {
                    Jenis_Kereta = "Ekonomi";
                } else if ("Bisnis".equals(rs.getString(5))){
                    Jenis_Kereta = "Bisnis";
                } else {
                    Jenis_Kereta = "Eksekutif";
                }
                String Tanggal_berangkat = rs.getString(6);
                String Waktu_berangkat = "";
                if ("09.00".equals(rs.getString(7))) {
                    Waktu_berangkat = "09.00";
                } else if ("12.00".equals(rs.getString(7))) {
                    Waktu_berangkat = "12.00";
                } else if ("14.00".equals(rs.getString(7))) {
                    Waktu_berangkat = "14.00";
                } else {
                    Waktu_berangkat = "16.00";
                }
                
                String Tempat_duduk = "";
                if ("A1".equals(rs.getString(8))) {
                    Tempat_duduk = "A1";
                } else if ("A2".equals(rs.getString(8))) {
                    Tempat_duduk = "A2";
                } else if ("A3".equals(rs.getString(8))) {
                    Tempat_duduk = "A3";
                } else if ("B1".equals(rs.getString(8))) {
                    Tempat_duduk = "B1";
                } else if ("B2".equals(rs.getString(8))) {
                    Tempat_duduk = "B2";
                } else if ("B3".equals(rs.getString(8))) {
                    Tempat_duduk = "B3";
                } else if ("C1".equals(rs.getString(8))) {
                    Tempat_duduk = "C1";
                } else if ("C2".equals(rs.getString(8))) {
                    Tempat_duduk = "C2";
                }else  {
                    Tempat_duduk = "C3";
                }
                String Harga = rs.getString(9);
    
                String data[] = {Nama,No_identitas,Stasiun_awal,Tujuan,Jenis_Kereta,Tanggal_berangkat,Waktu_berangkat,Tempat_duduk, Harga};
                dtm.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTable1.setModel(dtm);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Cari;
    private javax.swing.JTextField Harga;
    private javax.swing.JTextField Identitas;
    private javax.swing.JComboBox<String> JK;
    private javax.swing.JTextField Nama;
    private javax.swing.JComboBox<String> SA;
    private javax.swing.JComboBox<String> ST;
    private javax.swing.JComboBox<String> T;
    private javax.swing.JComboBox<String> TD;
    private com.toedter.calendar.JDateChooser Waktu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
